consumers:
  names: ["Marie-Anne", "Johann", "Alain", "Luc"]
  smartmeters:
    [
      "LU0000010637000000000000070232020",
      "LU0000010637000000000000070232021",
      "LU0000010637000000000000070232018",
      "LU0000010637000000000000070314570",
    ]
  obiscode: ["1-65:1.29.2", "1-65:1.29.2", "1-65:1.29.2", "1-65:1.29.2"]
  emails:
    ["muckil@web.de", "gillwe@pt.lu", "wenneral@gmail.com", "lschaus@pt.lu"]

producers:
  names: ["Madalin", "Luc", "Alain"]
  smartmeters:
    [
      "LU0000010637000000000000770392841",
      "LU0000010637000000000000770314570",
      "LU0000010637000000000000770232018",
    ]
  obiscode: ["1-65:2.29.2", "1-65:2.29.2", "1-65:2.29.2"]
  emails: ["m.amzolini@gmail.com", "lschaus@pt.lu"]
leneda:
  url: "https://api.leneda.lu"
  energyId:
    header: "X-ENERGY-ID"
    value: "LUXE-MA-DU-ZPUGN"
  apiKey:
    header: "X-API-KEY"
    value: "e0e3f107-1836-4717-a090-d1863fe9f30c"
  api:
    meteringData: "/api/metering-points/" #{meteringPointCode}/time-series"
pricing:
  kwhprice: 0.11 # price agrred on between members
  normalfee: 0.07 # price paid for the produced energy
  network: 0.0759 # network fee
  consumerprice: 0.15 # price paid by the consumer (energyrevolt)
  tax: 0.0010
  compensation: -0.0376 #Preisdeckel
  tva: 0.08 # 8%
